version: '3.8'

services:
  # Go API Server
  goserver:
    build: .
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_DATABASE=laravel_app
      - DB_USERNAME=laravel_user
      - DB_PASSWORD=laravel_password
      - APP_ENV=local
      - PORT=8080
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - laravel-network

  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: laravel_app
      POSTGRES_USER: laravel_user
      POSTGRES_PASSWORD: laravel_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/migrations:/docker-entrypoint-initdb.d/
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U laravel_user -d laravel_app"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - laravel-network

volumes:
  postgres_data:

networks:
  laravel-network:
    external: true